# Discord Channel ID where the bot will send messages. Ensure the bot has permissions to send messages in this channel.
chanid: ""

# Bot token for authenticating with Discord. Keep this secure and do not share it.
token: ""

# Time interval in ticks (1 second = 20 ticks). For example, 12000 ticks equals 10 minutes.
time: 12000

# Set to true for messages to be sent automatically on a schedule, defined by 'time'. 
# Set to false if messages should only be sent via command.
repeat: true

# Enable or disable embedded messages for the scheduled (repeat) messages.
embed: true

# Enable or disable embedded messages when triggered by a command.
embedCmd: true

# Title of the embed, shown at the top of the message.
embedTitle: "Stats"

# URL for the image shown in the embed. Must be less than 2000 characters.
imgURL: "https://png.pngtree.com/background/20230613/original/pngtree-digital-technology-background-with-dark-lines-and-lines-picture-image_3386207.jpg"

# Command name used to trigger the bot on Discord. Must be lowercase only.
cmdNameForDiscord: "serverstats"
