name: ServerStatsSender
version: '1.0.1'
main: com.lent.serverstatssender.Main
api-version: '1.21'
libraries:
  - net.dv8tion:JDA:5.1.2
  - org.jetbrains.kotlin:kotlin-stdlib:2.1.0-Beta2
commands:
  sssactivate:
  sssreload: